### ISSUE TITLE
de.daslaboratorium.machinelearning.classifier.Classifier#featureProbability

### ISSUE THREAD

**Issue by pengfeis** [ptnplanet/Java-Naive-Bayes-Classifier#10]
via Classifier code i guess the featureProbability should not bigger than 1.0, but I found that if have 2+ "I" in the trainning material, I got the  featureProbability more than 1.0+. following is the code snippet:
in test change the learn material like:
  ` final String[] positiveText = "I happy now, I like you".split("\\s");`

print some info in featureProbability :

` float featureCount = (float) this.featureCount(feature, category);`
 `float categoryCount = (float) this.categoryCount(category);`
`System.out.println("raw p(f|c) " + String.valueOf(feature) + featureCount + "->" + String.valueOf(category) + categoryCount +  "->" + featureCount / categoryCount); return featureCount / categoryCount;`

then the output:

`raw p(f|c) I2.0->positive1.0->2.0`

does the result is correct? or can you clearfy what the math model to calc p(f|c)?

**Comment by ptnplanet** [comment]
Hi @pengfeis.
I admit that the default feature probability calculation was counter-intuitive. It calculated the probability a feature occurred in a given category against the number of learning sets for this category. I have exchange it in 1.0.5 for a more intuitive probability of a feature occurring in a given category against the total number of occurrences of that feature.
Please be aware of the `IFeatureProbability` interface that you can implement for your own probability calculator. You can pass your own calculator to the `Classifier.featureWeighedAverage` method.
BR
