### ISSUE TITLE
Classifier is not serializable

### ISSUE THREAD

**Issue by mehdi-mbl** [ptnplanet/Java-Naive-Bayes-Classifier#12]
I tried to serialize a classifier I train on my data set but it turn out that it uses a non serializable object. The "Classifier" class in itself implements serializable but I am not quit sure which class it uses does not. 
Thank you and great work with the naive Bayes classifier.

**Comment by ptnplanet** [comment]
Closed with [v1.0.7](https://github.com/ptnplanet/Java-Naive-Bayes-Classifier/releases/tag/1.0.7)
