### ISSUE TITLE
classifying only to particular class

### ISSUE THREAD

**Issue by Hemanthvinayac** [ptnplanet/Java-Naive-Bayes-Classifier#4]
I am using double[] as feature instead of string in runnableExample, but the feature of class -ve is still classifying as +ve.  And in featureCount, I am not getting any value other than null.

**Comment by ptnplanet** [comment]
Hello, do you still have this issue? If so, could you please provide me with a runnable example using double[] as feature?

**Comment by Hemanthvinayac** [comment]
Issue is solved, thanks
